name: shirloin

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker Imge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #checkout to the repository on the build machine
        uses: actions/checkout@v2

      - #Login to Docker Hub using secret in github
        name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - #Create env
        name: Create .env
        run: |
          touch .env
          echo VITE_SERVICE_ID = ${{secrets.VITE_SERVICE_ID}} >> .env
          echo VITE_TEMPLATE_ID = ${{secrets.VITE_TEMPLATE_ID}} >> .env
          echo VITE_USER_ID = ${{secrets.VITE_USER_ID}} >> .env

      - #Create a build kit builder instance
        name: Set up docker Build
        uses: docker/setup-buildx-action@v2

      - #Build the container image and push it to Docker Hub with name shirloin
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/shirloin:latest

      - #Deploy To VPS
        name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          username: ${{secrets.VPS_USERNAME}}
          password: ${{secrets.VPS_PASSWORD}}
          script: |
            mkdir shirloin
            cd shirloin
            curl -o docker-compose.yml https://raw.githubusercontent.com/shirloin/portofolio/main/docker-compose.yml
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/shirloin:latest
            docker compose up -d
